#!/bin/bash

dir="$HOME/Pictures/wallpapers/"

usage() {
	echo "USAGE: "
	echo "-h   display this help  "
	echo "-v   display version "
	echo "-r   set random wallpaper "
	echo "-s   select wallpaper "

}

options() {
while getopts "rvsh:" flag
do
	case "$flag" in 
		v)
			echo "v1.2" && exit;;
		r)
			wal -q -i "$dir";;
		s)
			wpr="$(sxiv -r "$dir" -o)" 
			wal -q -i "$wpr" ;;
		h)
			usage ;;
		?)
			usage && exit 1 ;;		
	esac
done 
}
options "$@"
pywalfox update;
cd && ./alacrittypywal.sh >/dev/null 2>&1 ; 
cp .cache/wal/colors.Xresources $HOME/.Xresources
awesome-client 'awesome.restart()' >/dev/null 2>&1
cd misc/ChromiumPywal/ && ./generate-theme.sh
cd
