#!/bin/sh

if [ -z "$1" ]; then
    url="$(xclip -o)"
else 
    url="$1"
fi

case "$url" in 
    *mkv|*webm|*mp4|*youtube.com/watch*|*youtube.com/playlist*|*youtube.com/shorts*|*youtu.be*|*odysee.com*)
	setsid -f mpv -quiet "$url" > /dev/null 2>&1 ;;
     *pdf|*cbz|*cbr)
        curl -sL "$url" > "/tmp/$(echo "$url" | sed "s/.*\/ //;s/%20/ /g")" &&mupdf "/tmp/$(echo "$url" | sed "s/.*\/ //;s/%20/ /g")" >/dev/null 2>&1 & ;;
        *)
      readable -o /tmp/x.html -s ~/.newsboat/dark.css "$url" >/dev/null 2>&1 && setsid -f qutebrowser /tmp/x.html >/dev/null 2>&1
esac
